name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3.4.0
      with:
        username: l3tum
        password: ${{secrets.DOCKER_PAT}}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag l3tum/nomad-consul-pi:latest --platform linux/arm64 
    - name: Push the Docker image
      run: docker push l3tum/nomad-consul-pi
